layout_spectrum: 0.83331
typography_spectrum: 0.8795483037829399
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1875
  lightness: 0.7536341480445117
  saturation: 0.28853699192404747
  rhythmicContrast: 0.490370579296723
name: Life of Outi
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
purpose: []
title: Life of Outi
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
