typography_spectrum: 0.8795483037829399
content_rating:
  adult: false
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1875
  lightness: 0.7536341480445117
  saturation: 0.28853699192404747
  rhythmicContrast: 0.490370579296723
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.83331
analytics: {}
author:
  name: ''
  url: ''
  email: ''
name: Life of Outi
cta: {}
navigation:
  - name: Family Robotics
    id: 1f0cccc8-d66e-4218-9403-a5dc8e6ea5b6
    type: content
title: Life of Outi
purpose: []
